server:
  port:8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://mysql-standalone:3306/blog?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: ms
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: select 1